assert(_VERSION == "Lua 5.4", "lua54_stdlib_edges.lua must run in Lua 5.4 compat mode")
if type(jit) == "table" and type(jit.off) == "function" then jit.off() end

local cases = {
  { "base.assert.noargs", "return assert()", err = "bad argument #1 to 'assert' (value expected)" },
  { "base.assert.false", "return assert(false, 'x', 2)", err = "x" },
  { "base.assert.trueholes", "return assert(true, nil, 'x')", ok = { "boolean:true", "nil:nil", "string:x" } },
  { "base.collectgarbage.badopt", "return collectgarbage('bad')", err = "bad argument #1 to 'collectgarbage' (invalid option 'bad')" },
  { "base.collectgarbage.badarg", "return collectgarbage(true)", err = "bad argument #1 to 'collectgarbage' (string expected, got boolean)" },
  { "base.collectgarbage.step.badarg", "return collectgarbage('step', true)", err = "bad argument #2 to 'collectgarbage' (number expected, got boolean)" },
  { "base.collectgarbage.step.frac", "return collectgarbage('step', 1.2)", err = "bad argument #2 to 'collectgarbage' (number has no integer representation)" },
  { "base.collectgarbage.nil.extra", "return collectgarbage(nil, true)", ok = { "number:0" } },
  { "base.collectgarbage.count.extra", "return type(collectgarbage('count', true))", ok = { "string:number" } },
  { "base.collectgarbage.stop.restart.extra", "collectgarbage('restart'); local before = collectgarbage('isrunning'); collectgarbage('stop', true); local stopped = collectgarbage('isrunning', true); collectgarbage('restart', true); local after = collectgarbage('isrunning'); return before, stopped, after", ok = { "boolean:true", "boolean:false", "boolean:true" } },
  { "base.collectgarbage.setpause.str", "local old = collectgarbage('setpause', '150'); local new = collectgarbage('setpause', old); return type(old), type(new), new > 0", ok = { "string:number", "string:number", "boolean:true" } },
  { "base.collectgarbage.setstepmul.str", "local old = collectgarbage('setstepmul', '200'); local new = collectgarbage('setstepmul', old); return type(old), new", ok = { "string:number", "number:200" } },
  { "base.collectgarbage.mode.roundtrip", "collectgarbage('incremental'); local oldgen = collectgarbage('generational'); local oldinc = collectgarbage('incremental'); local restore = collectgarbage('generational'); return oldgen, oldinc, restore", ok = { "string:incremental", "string:generational", "string:incremental" } },
  { "base.collectgarbage.minor.badopt", "return collectgarbage('minor')", err = "bad argument #1 to 'collectgarbage' (invalid option 'minor')" },
  { "base.dofile.bad", "return dofile(true)", err = "bad argument #1 to 'dofile' (string expected, got boolean)" },
  { "base.error.noarg", "return error()", err = "nil" },
  { "base.error.level.bad", "return error('x', true)", err = "bad argument #2 to 'error' (number expected, got boolean)" },
  { "base.error.level.float", "return error('x', 1.2)", err = "bad argument #2 to 'error' (number has no integer representation)" },
  { "base.getmetatable.noarg", "return getmetatable()", err = "bad argument #1 to 'getmetatable' (value expected)" },
  { "base.getmetatable.protected", "local t = setmetatable({}, { __metatable = 'locked' }); return getmetatable(t)", ok = { "string:locked" } },
  { "base.ipairs.nil", "return ipairs(nil)", ok = { "function", "nil:nil", "number:0" } },
  { "base.ipairs.sameiter", "return ipairs({}) == ipairs({})", ok = { "boolean:true" } },
  { "base.ipairs.emptyiter", "local iter, state, index = ipairs({}); return select('#', iter(state, index)), iter(state, index)", ok = { "number:1", "nil:nil" } },
  { "base.load.badchunk", "return load(true)", err = "bad argument #1 to 'load' (function expected, got boolean)" },
  { "base.load.badmode", "return load('', 'x', true)", err = "bad argument #3 to 'load' (string expected, got boolean)" },
  { "base.load.badenv", "return load('', 'x', 't', true)", ok = { "function" } },
  { "base.load.reader.bool", "local done = false; return load(function() if not done then done = true; return true end end)", ok = { "nil:nil", "string:base.load.reader.bool:1: reader function must return a string" } },
  { "base.load.reader.number", "local done = false; return load(function() if not done then done = true; return 123 end end)", ok = { "nil:nil", "string:(load):1: unexpected symbol near '123'" } },
  { "base.load.reader.empty", "local done = false; return load(function() if not done then done = true; return '' end end)", ok = { "function" } },
  { "base.load.reader.nilfirst", "return load(function() return nil end)", ok = { "function" } },
  { "base.load.mode.bintext", "return load('return 1', 'chunk', 'b')", ok = { "nil:nil", "string:attempt to load a text chunk (mode is 'b')" } },
  { "base.load.mode.textbin", "local f = function() return 1 end; return load(string.dump(f), 'chunk', 't')", ok = { "nil:nil", "string:attempt to load a binary chunk (mode is 't')" } },
  { "base.load.mode.badchar", "return load('', 'chunk', 'x')", ok = { "nil:nil", "string:attempt to load a text chunk (mode is 'x')" } },
  { "base.loadfile.badmode", "return loadfile(nil, true)", err = "bad argument #2 to 'loadfile' (string expected, got boolean)" },
  { "base.next.nil", "return next(nil)", err = "bad argument #1 to 'next' (table expected, got nil)" },
  { "base.next.empty", "return select('#', next({})), next({})", ok = { "number:1", "nil:nil" } },
  { "base.pairs.nil", "return pairs(nil)", ok = { "function", "nil:nil", "nil:nil" } },
  { "base.pcall.noarg", "return pcall()", err = "bad argument #1 to 'pcall' (value expected)" },
  { "base.pcall.noncall", "return pcall(1)", ok = { "boolean:false", "string:attempt to call a number value" } },
  { "base.pcall.values", "local ok, a, b, c = pcall(function() return 'a', nil, 'c' end); return ok, a, b, c", ok = { "boolean:true", "string:a", "nil:nil", "string:c" } },
  { "base.rawequal.one", "return rawequal(1)", err = "bad argument #2 to 'rawequal' (value expected)" },
  { "base.rawequal.values", "return rawequal(1, 1.0), rawequal({}, {})", ok = { "boolean:true", "boolean:false" } },
  { "base.rawget.noarg", "return rawget()", err = "bad argument #1 to 'rawget' (table expected, got no value)" },
  { "base.rawget.nokey", "return rawget({})", err = "bad argument #2 to 'rawget' (value expected)" },
  { "base.rawget.missing", "return rawget({ a = 1 }, 'b')", ok = { "nil:nil" } },
  { "base.rawlen.noarg", "return rawlen()", err = "bad argument #1 to 'rawlen' (table or string expected, got no value)" },
  { "base.rawlen.bad", "return rawlen(true)", err = "bad argument #1 to 'rawlen' (table or string expected, got boolean)" },
  { "base.rawlen.string", "return rawlen('abc')", ok = { "number:3" } },
  { "base.rawlen.tablemeta", "local t = setmetatable({ 1, 2 }, { __len = function() return 99 end }); return rawlen(t), #t", ok = { "number:2", "number:99" } },
  { "base.rawset.noarg", "return rawset()", err = "bad argument #1 to 'rawset' (table expected, got no value)" },
  { "base.rawset.noval", "return rawset({}, 1)", err = "bad argument #3 to 'rawset' (value expected)" },
  { "base.rawset.return", "local t = {}; return rawset(t, 'a', 1) == t, t.a", ok = { "boolean:true", "number:1" } },
  { "base.rawset.nilkey", "return rawset({}, nil, 1)", err = "table index is nil" },
  { "base.select.noarg", "return select()", err = "bad argument #1 to 'select' (number expected, got no value)" },
  { "base.select.bad", "return select(0, 1)", err = "bad argument #1 to 'select' (index out of range)" },
  { "base.select.frac", "return select(1.2, 'a', 'b')", err = "bad argument #1 to 'select' (number has no integer representation)" },
  { "base.select.negative", "return select(-1, 'a', nil, 'c')", ok = { "string:c" } },
  { "base.select.strpos", "return select('2', 'a', 'b', 'c')", ok = { "string:b", "string:c" } },
  { "base.select.count", "return select('#', 'a', nil, 'c')", ok = { "number:3" } },
  { "base.select.widepos", "return select('#', select(1099511627776, 'a', 'b'))", ok = { "number:0" } },
  { "base.select.widestr", "return select('#', select('1099511627776', 'a', 'b'))", ok = { "number:0" } },
  { "base.select.wideneg", "return select(-1099511627776, 'a', 'b')", err = "bad argument #1 to 'select' (index out of range)" },
  { "base.setmetatable.noarg", "return setmetatable()", err = "bad argument #1 to 'setmetatable' (table expected, got no value)" },
  { "base.setmetatable.bad2", "return setmetatable({}, true)", err = "bad argument #2 to 'setmetatable' (nil or table expected, got boolean)" },
  { "base.setmetatable.return", "local t = {}; return setmetatable(t, {}) == t", ok = { "boolean:true" } },
  { "base.setmetatable.protected", "local t = setmetatable({}, { __metatable = 'locked' }); return setmetatable(t, {})", err = "cannot change a protected metatable" },
  { "base.tonumber.badbase", "return tonumber('10', 1)", err = "bad argument #2 to 'tonumber' (base out of range)" },
  { "base.tonumber.badbasebool", "return tonumber('10', true)", err = "bad argument #2 to 'tonumber' (number expected, got boolean)" },
  { "base.tonumber.floatbase", "return tonumber('10', 10.2)", err = "bad argument #2 to 'tonumber' (number has no integer representation)" },
  { "base.tonumber.widebase", "return tonumber('10', 1099511627776)", err = "bad argument #2 to 'tonumber' (base out of range)" },
  { "base.tonumber.noarg", "return tonumber()", err = "bad argument #1 to 'tonumber' (value expected)" },
  { "base.tonumber.table", "return tonumber({})", ok = { "nil:nil" } },
  { "base.tonumber.int", "return math.type(tonumber('1')), tonumber('1')", ok = { "string:integer", "number:1" } },
  { "base.tonumber.float", "return math.type(tonumber('1.0')), tonumber('1.0')", ok = { "string:float", "number:1.0" } },
  { "base.tonumber.base10big", "return math.type(tonumber('\\t10000000000\\t', 10)), tonumber('\\t10000000000\\t', 10)", ok = { "string:integer", "number:10000000000" } },
  { "base.tonumber.base36", "return tonumber('z', 36)", ok = { "number:35" } },
  { "base.tonumber.basefloatnil", "return tonumber('1.0', 10)", ok = { "nil:nil" } },
  { "base.tonumber.basenul", "return tonumber('1\\0', 2)", ok = { "nil:nil" } },
  { "base.tostring.noarg", "return tostring()", err = "bad argument #1 to 'tostring' (value expected)" },
  { "base.tostring.metamethod", "return tostring(setmetatable({}, { __tostring = function() return 'custom' end }))", ok = { "string:custom" } },
  { "base.tostring.badmeta", "return tostring(setmetatable({}, { __tostring = function() return {} end }))", err = "'__tostring' must return a string" },
  { "base.type.noarg", "return type()", err = "bad argument #1 to 'type' (value expected)" },
  { "base.warn.noarg", "return warn()", err = "bad argument #1 to 'warn' (string expected, got no value)" },
  { "base.warn.bad", "return warn({})", err = "bad argument #1 to 'warn' (string expected, got table)" },
  { "base.xpcall.nohandler", "return xpcall(function() end)", err = "bad argument #2 to 'xpcall' (function expected, got no value)" },
  { "base.xpcall.badhandler", "return xpcall(function() end, true)", err = "bad argument #2 to 'xpcall' (function expected, got boolean)" },
  { "base.xpcall.values", "local ok, a, b = xpcall(function() return 'a', nil end, function(e) return e end); return ok, a, b", ok = { "boolean:true", "string:a", "nil:nil" } },

  { "coroutine.close.noarg", "return coroutine.close()", err = "bad argument #1 to 'close' (thread expected, got no value)" },
  { "coroutine.close.bad", "return coroutine.close(true)", err = "bad argument #1 to 'close' (thread expected, got boolean)" },
  { "coroutine.close.fresh", "local co = coroutine.create(function() return 'fresh' end); local r = table.pack(coroutine.close(co)); return r.n, r[1], coroutine.status(co)", ok = { "number:1", "boolean:true", "string:dead" } },
  { "coroutine.close.yielded", "local co = coroutine.create(function() coroutine.yield('pause') end); local ok, v = coroutine.resume(co); local r = table.pack(coroutine.close(co)); return ok, v, r.n, r[1], coroutine.status(co)", ok = { "boolean:true", "string:pause", "number:1", "boolean:true", "string:dead" } },
  { "coroutine.close.tbc.nilerr", "local seen, same, obj; obj = setmetatable({}, { __close = function(self, err) same = self == obj; seen = err end }); local co = coroutine.create(function() local x <close> = obj; coroutine.yield('pause') end); local ok, v = coroutine.resume(co); local r = table.pack(coroutine.close(co)); return ok, v, same, seen, r.n, r[1], coroutine.status(co)", ok = { "boolean:true", "string:pause", "boolean:true", "nil:nil", "number:1", "boolean:true", "string:dead" } },
  { "coroutine.close.tbc.error", "local co = coroutine.create(function() local x <close> = setmetatable({}, { __close = function() error('closeerr', 0) end }); coroutine.yield('pause') end); coroutine.resume(co); local ok, err = coroutine.close(co); return ok, err, coroutine.status(co)", ok = { "boolean:false", "string:closeerr", "string:dead" } },
  { "coroutine.close.tbc.reclose", "local co = coroutine.create(function() local x <close> = setmetatable({}, { __close = function() error('closeerr', 0) end }); coroutine.yield('pause') end); coroutine.resume(co); local ok, err = coroutine.close(co); local r = table.pack(coroutine.close(co)); return ok, err, r.n, r[1], coroutine.status(co)", ok = { "boolean:false", "string:closeerr", "number:1", "boolean:true", "string:dead" } },
  { "coroutine.close.tbc.errorobject", "local marker = {}; local co = coroutine.create(function() local x <close> = setmetatable({}, { __close = function() error(marker, 0) end }); coroutine.yield() end); coroutine.resume(co); local ok, err = coroutine.close(co); return ok, err == marker, type(err), coroutine.status(co)", ok = { "boolean:false", "boolean:true", "string:table", "string:dead" } },
  { "coroutine.close.dead", "local co = coroutine.create(function() return 'done' end); coroutine.resume(co); local r = table.pack(coroutine.close(co)); return r.n, r[1], coroutine.status(co)", ok = { "number:1", "boolean:true", "string:dead" } },
  { "coroutine.close.running", "return coroutine.close(coroutine.running())", err = "cannot close a running coroutine" },
  { "coroutine.create.noarg", "return coroutine.create()", err = "bad argument #1 to 'create' (function expected, got no value)" },
  { "coroutine.create.bad", "return coroutine.create(true)", err = "bad argument #1 to 'create' (function expected, got boolean)" },
  { "coroutine.create.callable", "return coroutine.create(setmetatable({}, { __call = function() end }))", err = "bad argument #1 to 'create' (function expected, got table)" },
  { "coroutine.resume.noarg", "return coroutine.resume()", err = "bad argument #1 to 'resume' (thread expected, got no value)" },
  { "coroutine.resume.badthread", "return coroutine.resume(true)", err = "bad argument #1 to 'resume' (thread expected, got boolean)" },
  { "coroutine.resume.values", "local co = coroutine.create(function(a, b) return a, nil, b end); local ok, a, b, c = coroutine.resume(co, 'x', 'y'); return ok, a, b, c, coroutine.status(co)", ok = { "boolean:true", "string:x", "nil:nil", "string:y", "string:dead" } },
  { "coroutine.resume.dead", "local co = coroutine.create(function() end); coroutine.resume(co); return coroutine.resume(co)", ok = { "boolean:false", "string:cannot resume dead coroutine" } },
  { "coroutine.resume.yieldvalues", "local co = coroutine.create(function(a) local x, y = coroutine.yield('out', nil); return a, x, y end); local ok1, a, b = coroutine.resume(co, 'in'); local ok2, c, d, e = coroutine.resume(co, 'r1', 'r2'); return ok1, a, b, ok2, c, d, e", ok = { "boolean:true", "string:out", "nil:nil", "boolean:true", "string:in", "string:r1", "string:r2" } },
  { "coroutine.running.main", "local co, ismain = coroutine.running(); return coroutine.status(co), ismain, coroutine.isyieldable(), coroutine.isyieldable(co)", ok = { "string:running", "boolean:true", "boolean:false", "boolean:false" } },
  { "coroutine.running.extra", "return coroutine.running(true)", ok = { "thread", "boolean:true" } },
  { "coroutine.status.noarg", "return coroutine.status()", err = "bad argument #1 to 'status' (thread expected, got no value)" },
  { "coroutine.status.dead", "local co = coroutine.create(function() end); coroutine.resume(co); return coroutine.status(co)", ok = { "string:dead" } },
  { "coroutine.wrap.bad", "return coroutine.wrap(true)", err = "bad argument #1 to 'wrap' (function expected, got boolean)" },
  { "coroutine.wrap.callable", "return coroutine.wrap(setmetatable({}, { __call = function() end }))", err = "bad argument #1 to 'wrap' (function expected, got table)" },
  { "coroutine.wrap.values", "local f = coroutine.wrap(function() return 'x', nil end); return f()", ok = { "string:x", "nil:nil" } },
  { "coroutine.wrap.yieldvalues", "local f = coroutine.wrap(function() local x = coroutine.yield('pause', nil); return x, nil end); local a, b = f(); local c, d = f('go'); return a, b, c, d", ok = { "string:pause", "nil:nil", "string:go", "nil:nil" } },
  { "coroutine.isyieldable.bad", "return coroutine.isyieldable(true)", err = "bad argument #1 to 'isyieldable' (thread expected, got boolean)" },
  { "coroutine.isyieldable.yielded", "local co = coroutine.create(function() coroutine.yield() end); coroutine.resume(co); return coroutine.isyieldable(co)", ok = { "boolean:true" } },
  { "coroutine.yield.main", "return coroutine.yield()", err = "attempt to yield from outside a coroutine" },
  { "coroutine.yield.values", "local co = coroutine.create(function() return coroutine.yield(nil, 'x') end); local ok, a, b = coroutine.resume(co); return ok, a, b", ok = { "boolean:true", "nil:nil", "string:x" } },

  { "debug.gethook.bad", "return debug.gethook(true)", ok = { "nil:nil" } },
  { "debug.gethook.none", "return select('#', debug.gethook()), debug.gethook()", ok = { "number:1", "nil:nil" } },
  { "debug.gethook.co.none", "local co = coroutine.create(function() end); return select('#', debug.gethook(co)), debug.gethook(co)", ok = { "number:1", "nil:nil" } },
  { "debug.getinfo.badlevel", "return debug.getinfo(1.2)", err = "bad argument #1 to 'getinfo' (number has no integer representation)" },
  { "debug.getinfo.widelevel", "return debug.getinfo(1099511627776, 'S').what", ok = { "string:C" } },
  { "debug.getinfo.maxlevel", "return debug.getinfo(math.maxinteger)", ok = { "nil:nil" } },
  { "debug.getinfo.badwhat", "return debug.getinfo(1, 'z')", err = "bad argument #2 to 'getinfo' (invalid option)" },
  { "debug.getinfo.badgtlevel", "return debug.getinfo(1, '>')", err = "bad argument #2 to 'getinfo' (invalid option '>')" },
  { "debug.getinfo.badgtfunc", "return debug.getinfo(function() end, '>')", err = "bad argument #2 to 'getinfo' (invalid option '>')" },
  { "debug.getinfo.funcu", "local function f(a, ...) return a end; local i = debug.getinfo(f, 'u'); return i.nparams, i.isvararg", ok = { "number:1", "boolean:true" } },
  { "debug.getlocal.badarg", "return debug.getlocal(true, 1)", err = "bad argument #1 to 'getlocal' (number expected, got boolean)" },
  { "debug.getlocal.missing", "return debug.getlocal(1, 999)", ok = { "nil:nil" } },
  { "debug.getlocal.co.valid", "local co = coroutine.create(function(a) local x = a + 1; coroutine.yield(x); return x end); coroutine.resume(co, 41); local n1, v1 = debug.getlocal(co, 1, 1); local n2, v2 = debug.getlocal(co, 1, 2); return n1, v1, n2, v2", ok = { "string:a", "number:41", "string:x", "number:42" } },
  { "debug.getmetatable.noarg", "return debug.getmetatable()", err = "bad argument #1 to 'getmetatable' (value expected)" },
  { "debug.getmetatable.plain", "return debug.getmetatable({})", ok = { "nil:nil" } },
  { "debug.getregistry.extra", "return debug.getregistry(1)", ok = { "table" } },
  { "debug.getupvalue.badfunc", "return debug.getupvalue(true, 1)", err = "bad argument #1 to 'getupvalue' (function expected, got boolean)" },
  { "debug.getupvalue.cfunc", "return select('#', debug.getupvalue(print, 1))", ok = { "number:0" } },
  { "debug.getupvalue.valid", "local x = 3; local function f() return x end; return debug.getupvalue(f, 1)", ok = { "string:x", "number:3" } },
  { "debug.getuservalue.noarg", "return debug.getuservalue()", ok = { "nil:nil" } },
  { "debug.getuservalue.nil", "return debug.getuservalue(nil)", ok = { "nil:nil" } },
  { "debug.getuservalue.bool", "return debug.getuservalue(true)", ok = { "nil:nil" } },
  { "debug.getuservalue.badslot", "return debug.getuservalue({}, true)", err = "bad argument #2 to 'getuservalue' (number expected, got boolean)" },
  { "debug.sethook.badthread", "return debug.sethook(true)", err = "bad argument #2 to 'sethook' (string expected, got no value)" },
  { "debug.sethook.badmask", "return debug.sethook(function() end, 'z')", ok = {} },
  { "debug.sethook.countstr", "return debug.sethook(function() end, '', '3')", ok = {} },
  { "debug.sethook.count0", "local f = function() end; debug.sethook(f, '', 0); return select('#', debug.gethook()), debug.gethook()", ok = { "number:1", "nil:nil" } },
  { "debug.sethook.count1", "local f = function() end; debug.sethook(f, '', 1); local h, mask, count = debug.gethook(); debug.sethook(); return type(h), mask, count", ok = { "string:function", "string:", "number:1" } },
  { "debug.sethook.countfrac", "return debug.sethook(function() end, '', 1.2)", err = "bad argument #3 to 'sethook' (number has no integer representation)" },
  { "debug.setcstacklimit.noarg", "return debug.setcstacklimit()", err = "bad argument #1 to 'setcstacklimit' (number expected, got no value)" },
  { "debug.setcstacklimit.bad", "return debug.setcstacklimit(true)", err = "bad argument #1 to 'setcstacklimit' (number expected, got boolean)" },
  { "debug.setcstacklimit.frac", "return debug.setcstacklimit(1.2)", err = "bad argument #1 to 'setcstacklimit' (number has no integer representation)" },
  { "debug.setcstacklimit.zero", "return type(debug.setcstacklimit(0))", ok = { "string:number" } },
  { "debug.setlocal.badarg", "return debug.setlocal(true, 1, 2)", err = "bad argument #1 to 'setlocal' (number expected, got boolean)" },
  { "debug.setlocal.missing", "return debug.setlocal(1, 999, 'x')", ok = { "nil:nil" } },
  { "debug.setlocal.co.valid", "local co = coroutine.create(function(a) local x = a + 1; coroutine.yield(x); return x end); coroutine.resume(co, 41); local name = debug.setlocal(co, 1, 2, 99); local ok, v = coroutine.resume(co); return name, ok, v", ok = { "string:x", "boolean:true", "number:99" } },
  { "debug.setmetatable.noarg", "return debug.setmetatable()", err = "bad argument #2 to 'setmetatable' (nil or table expected, got no value)" },
  { "debug.setmetatable.bad2", "return debug.setmetatable({}, true)", err = "bad argument #2 to 'setmetatable' (nil or table expected, got boolean)" },
  { "debug.setmetatable.return", "local t = {}; local mt = { tag = 1 }; return debug.setmetatable(t, mt) == t, getmetatable(t).tag", ok = { "boolean:true", "number:1" } },
  { "debug.setupvalue.badfunc", "return debug.setupvalue(true, 1, 2)", err = "bad argument #1 to 'setupvalue' (function expected, got boolean)" },
  { "debug.setupvalue.missing", "local function f() end; return select('#', debug.setupvalue(f, 1, 'hidden'))", ok = { "number:0" } },
  { "debug.setupvalue.cfunc", "return select('#', debug.setupvalue(print, 1, 'hidden'))", ok = { "number:0" } },
  { "debug.setupvalue.valid", "local x = 3; local function f() return x end; return debug.setupvalue(f, 1, 4), f()", ok = { "string:x", "number:4" } },
  { "debug.setuservalue.noarg", "return debug.setuservalue()", err = "bad argument #1 to 'setuservalue' (userdata expected, got no value)" },
  { "debug.setuservalue.badslot", "return debug.setuservalue({}, 1, true)", err = "bad argument #3 to 'setuservalue' (number expected, got boolean)" },
  { "debug.traceback.badthread", "return debug.traceback(true)", ok = { "boolean:true" } },
  { "debug.traceback.noargs", "return debug.traceback() ~= nil", ok = { "boolean:true" } },
  { "debug.traceback.widelevel", "return debug.traceback('m', 1099511627776):match('stack traceback') ~= nil", ok = { "boolean:true" } },
  { "debug.upvalueid.noarg", "return debug.upvalueid()", err = "bad argument #2 to 'upvalueid' (number expected, got no value)" },
  { "debug.upvalueid.badfunc.noidx", "return debug.upvalueid(true)", err = "bad argument #2 to 'upvalueid' (number expected, got no value)" },
  { "debug.upvalueid.badfunc", "return debug.upvalueid(true, 1)", err = "bad argument #1 to 'upvalueid' (function expected, got boolean)" },
  { "debug.upvalueid.missing0", "local function f() end; return select('#', debug.upvalueid(f, 0)), debug.upvalueid(f, 0)", ok = { "number:1", "nil:nil" } },
  { "debug.upvalueid.missing1", "local function f() end; return select('#', debug.upvalueid(f, 1)), debug.upvalueid(f, 1)", ok = { "number:1", "nil:nil" } },
  { "debug.upvalueid.cfunc", "return select('#', debug.upvalueid(print, 1)), debug.upvalueid(print, 1)", ok = { "number:1", "nil:nil" } },
  { "debug.upvalueid.valid", "local x = 1; local function f() return x end; return type(debug.upvalueid(f, 1)), debug.upvalueid(f, 1) == debug.upvalueid(f, 1)", ok = { "string:userdata", "boolean:true" } },
  { "debug.upvaluejoin.noarg", "return debug.upvaluejoin()", err = "bad argument #2 to 'upvaluejoin' (number expected, got no value)" },
  { "debug.upvaluejoin.badfunc.noidx", "return debug.upvaluejoin(true)", err = "bad argument #2 to 'upvaluejoin' (number expected, got no value)" },
  { "debug.upvaluejoin.badfunc1", "return debug.upvaluejoin(true, 1, function() end, 1)", err = "bad argument #1 to 'upvaluejoin' (function expected, got boolean)" },
  { "debug.upvaluejoin.valid1.noarg2", "local x; local f = function() return x end; return debug.upvaluejoin(f, 1)", err = "bad argument #4 to 'upvaluejoin' (number expected, got no value)" },
  { "debug.upvaluejoin.valid1.badfunc2.noidx2", "local x; local f = function() return x end; return debug.upvaluejoin(f, 1, true)", err = "bad argument #4 to 'upvaluejoin' (number expected, got no value)" },
  { "debug.upvaluejoin.valid1.badfunc2", "local x; local f = function() return x end; return debug.upvaluejoin(f, 1, true, 1)", err = "bad argument #3 to 'upvaluejoin' (function expected, got boolean)" },
  { "debug.upvaluejoin.badfunc2", "return debug.upvaluejoin(function() end, 1, true, 1)", err = "bad argument #2 to 'upvaluejoin' (invalid upvalue index)" },
  { "debug.upvaluejoin.valid", "local x, y = 1, 2; local function f() return x end; local function g(v) if v ~= nil then y = v end return y end; local n = select('#', debug.upvaluejoin(f, 1, g, 1)); g(3); return n, f(), debug.upvalueid(f, 1) == debug.upvalueid(g, 1)", ok = { "number:0", "number:3", "boolean:true" } },

  { "io.close.dot.noself.tail", "local f = assert(io.tmpfile()); return f.close()", err = "bad argument #1 to 'close' (FILE* expected, got no value)" },
  { "io.read.dot.noself.tail", "local f = assert(io.tmpfile()); return f.read()", err = "bad argument #1 to 'read' (FILE* expected, got no value)" },
  { "io.write.dot.noself.tail", "local f = assert(io.tmpfile()); return f.write('x')", err = "bad argument #1 to 'write' (FILE* expected, got string)" },
  { "io.flush.dot.noself.tail", "local f = assert(io.tmpfile()); return f.flush()", err = "bad argument #1 to 'flush' (FILE* expected, got no value)" },
  { "io.seek.dot.noself.tail", "local f = assert(io.tmpfile()); return f.seek()", err = "bad argument #1 to 'seek' (FILE* expected, got no value)" },
  { "io.setvbuf.dot.noself.tail", "local f = assert(io.tmpfile()); return f.setvbuf('no')", err = "bad argument #1 to 'setvbuf' (FILE* expected, got string)" },
  { "io.lines.dot.noself.tail", "local f = assert(io.tmpfile()); return f.lines()", err = "bad argument #1 to 'lines' (FILE* expected, got no value)" },
  { "io.close.pcall.noself", "local f = assert(io.tmpfile()); local ok, err = pcall(f.close); if ok then error('unexpected success', 0) end; error(err, 0)", err = "bad argument #1 to '?' (FILE* expected, got no value)" },
  { "io.flush.pcall.noself", "local f = assert(io.tmpfile()); local ok, err = pcall(f.flush); if ok then error('unexpected success', 0) end; error(err, 0)", err = "bad argument #1 to '?' (FILE* expected, got no value)" },
  { "io.type.noarg", "return io.type()", err = "bad argument #1 to 'type' (value expected)" },
  { "io.type.pcall.noarg", "local ok, err = pcall(io.type); if ok then error('unexpected success', 0) end; error(err, 0)", err = "bad argument #1 to 'io.type' (value expected)" },
  { "io.type.nil", "return io.type(nil)", ok = { "nil:nil" } },
  { "io.type.bool", "return io.type(true)", ok = { "nil:nil" } },
  { "io.type.file", "local f = assert(io.tmpfile()); local r = io.type(f); f:close(); return r", ok = { "string:file" } },
  { "io.type.closed", "local f = assert(io.tmpfile()); f:close(); return io.type(f)", ok = { "string:closed file" } },
  { "io.open.noarg", "return io.open()", err = "bad argument #1 to 'open' (string expected, got no value)" },
  { "io.open.badmode", "return io.open('x', true)", err = "bad argument #2 to 'open' (string expected, got boolean)" },
  { "io.open.invalidmode", "return io.open('x', 'bad')", err = "bad argument #2 to 'open' (invalid mode)" },
  { "io.tmpfile.rw", "local f = assert(io.tmpfile()); f:write('abc'); f:seek('set'); local s = f:read('a'); f:close(); return s", ok = { "string:abc" } },
  { "io.input.noarg", "return io.type(io.input())", ok = { "string:file" } },
  { "io.output.noarg", "return io.type(io.output())", ok = { "string:file" } },
  { "io.input.bad", "return io.input(true)", err = "bad argument #1 to 'input' (FILE* expected, got boolean)" },
  { "io.output.bad", "return io.output(true)", err = "bad argument #1 to 'output' (FILE* expected, got boolean)" },
  { "io.close.bad", "return io.close(true)", err = "bad argument #1 to 'close' (FILE* expected, got boolean)" },
  { "io.file.close", "local f = assert(io.tmpfile()); return f:close()", ok = { "boolean:true" } },
  { "io.file.close.closed", "local f = assert(io.tmpfile()); f:close(); return f:close()", err = "attempt to use a closed file" },
  { "io.file.flush", "local f = assert(io.tmpfile()); local r = f:flush(); f:close(); return r", ok = { "boolean:true" } },
  { "io.file.flush.closed", "local f = assert(io.tmpfile()); f:close(); return f:flush()", err = "attempt to use a closed file" },
  { "io.file.read.closed", "local f = assert(io.tmpfile()); f:close(); return f:read('a')", err = "attempt to use a closed file" },
  { "io.file.write.closed", "local f = assert(io.tmpfile()); f:close(); return f:write('x')", err = "attempt to use a closed file" },
  { "io.lines.badpath", "return io.lines(true)", err = "bad argument #1 to 'lines' (string expected, got boolean)" },
  { "io.lines.iterator.badopt", "local name = os.tmpname(); local f = assert(io.open(name, 'w')); f:write('x'); f:close(); local it, _, _, fh = io.lines(name, true); local ok, err = pcall(it); if fh then fh:close() end; os.remove(name); if ok then error('unexpected success', 0) end; error(err, 0)", err = "bad argument #2 to '?' (string expected, got boolean)" },
  { "io.popen.badcmd", "return io.popen(true)", err = "bad argument #1 to 'popen' (string expected, got boolean)" },
  { "io.popen.badmode", "return io.popen('x', true)", err = "bad argument #2 to 'popen' (string expected, got boolean)" },
  { "io.popen.invalidmode", "return io.popen('x', 'bad')", err = "bad argument #2 to 'popen' (invalid mode)" },
  { "io.read.badfmt", "return io.read({})", err = "bad argument #1 to 'read' (string expected, got table)" },
  { "io.write.badarg", "return io.write({})", err = "bad argument #1 to 'write' (string expected, got table)" },
  { "io.file.read.badfmt", "local f = assert(io.tmpfile()); return f:read({})", err = "bad argument #1 to 'read' (string expected, got table)" },
  { "io.file.write.badarg", "local f = assert(io.tmpfile()); return f:write({})", err = "bad argument #1 to 'write' (string expected, got table)" },
  { "io.file.read.number", "local f = assert(io.tmpfile()); f:write('12.5 rest'); f:seek('set'); local n = f:read('n'); f:close(); return type(n), n", ok = { "string:number", "number:12.5" } },
  { "io.read.wide", "local f = assert(io.tmpfile()); return f:read(1099511627776)", err = "not enough memory" },
  { "io.read.wideneg", "local f = assert(io.tmpfile()); return f:read(-1099511627776)", err = "not enough memory" },
  { "io.seek.wide", "local f = assert(io.tmpfile()); return f:seek('set', 2147483648)", err = "bad argument #2 to 'seek' (not an integer in proper range)" },
  { "io.seek.widestr", "local f = assert(io.tmpfile()); return f:seek('set', '2147483648')", err = "bad argument #2 to 'seek' (not an integer in proper range)" },
  { "io.seek.current", "local f = assert(io.tmpfile()); f:write('abc'); local p = f:seek(); f:close(); return p", ok = { "number:3" } },
  { "io.seek.end", "local f = assert(io.tmpfile()); f:write('abc'); local p = f:seek('end'); f:close(); return p", ok = { "number:3" } },
  { "io.seek.strint", "local f = assert(io.tmpfile()); f:write('abc'); local p = f:seek('set', '2'); local s = f:read('a'); f:close(); return p, s", ok = { "number:2", "string:c" } },
  { "io.seek.badwhence", "local f = assert(io.tmpfile()); return f:seek('bad')", err = "bad argument #1 to 'seek' (invalid option 'bad')" },
  { "io.seek.pcall.badofs", "local f = assert(io.tmpfile()); local ok, err = pcall(f.seek, f, 'set', {}); if ok then error('unexpected success', 0) end; error(err, 0)", err = "bad argument #3 to '?' (number expected, got table)" },
  { "io.seek.dot.badofs", "local f = assert(io.tmpfile()); return f.seek(f, 'set', {})", err = "bad argument #3 to 'seek' (number expected, got table)" },
  { "io.seek.alias.badofs", "local f = assert(io.tmpfile()); local s = f.seek; return s(f, 'set', {})", err = "bad argument #3 to 's' (number expected, got table)" },
  { "io.setvbuf.no", "local f = assert(io.tmpfile()); local r = f:setvbuf('no'); f:close(); return r", ok = { "boolean:true" } },
  { "io.setvbuf.full.strsize", "local f = assert(io.tmpfile()); local r = f:setvbuf('full', '1024'); f:close(); return r", ok = { "boolean:true" } },
  { "io.setvbuf.badmode", "local f = assert(io.tmpfile()); return f:setvbuf('bad')", err = "bad argument #1 to 'setvbuf' (invalid option 'bad')" },
  { "io.setvbuf.fracsize", "local f = assert(io.tmpfile()); return f:setvbuf('full', 1.2)", err = "bad argument #2 to 'setvbuf' (number has no integer representation)" },
  { "io.setvbuf.pcall.badsize", "local f = assert(io.tmpfile()); local ok, err = pcall(f.setvbuf, f, 'full', {}); if ok then error('unexpected success', 0) end; error(err, 0)", err = "bad argument #3 to '?' (number expected, got table)" },
  { "io.setvbuf.dot.badsize", "local f = assert(io.tmpfile()); return f.setvbuf(f, 'full', {})", err = "bad argument #3 to 'setvbuf' (number expected, got table)" },
  { "io.setvbuf.alias.badsize", "local f = assert(io.tmpfile()); local s = f.setvbuf; return s(f, 'full', {})", err = "bad argument #3 to 's' (number expected, got table)" },

  { "math.abs.noarg", "return math.abs()", err = "bad argument #1 to 'abs' (number expected, got no value)" },
  { "math.abs.bad", "return math.abs(true)", err = "bad argument #1 to 'abs' (number expected, got boolean)" },
  { "math.abs.string", "return math.type(math.abs('-5')), math.abs('-5')", ok = { "string:float", "number:5.0" } },
  { "math.abs.strfloat", "return math.type(math.abs('-5.0')), math.abs('-5.0')", ok = { "string:float", "number:5.0" } },
  { "math.abs.negzero", "return math.type(math.abs(-0.0)), math.abs(-0.0)", ok = { "string:float", "number:0.0" } },
  { "math.abs.mininteger", "return math.type(math.abs(math.mininteger)), math.abs(math.mininteger) == math.mininteger", ok = { "string:integer", "boolean:true" } },
  { "math.asin.noarg", "return math.asin()", err = "bad argument #1 to 'asin' (number expected, got no value)" },
  { "math.asin.string", "return math.asin('0')", ok = { "number:0.0" } },
  { "math.acos.bad", "return math.acos(true)", err = "bad argument #1 to 'acos' (number expected, got boolean)" },
  { "math.acos.string", "return math.acos('1')", ok = { "number:0.0" } },
  { "math.sin.noarg", "return math.sin()", err = "bad argument #1 to 'sin' (number expected, got no value)" },
  { "math.sin.bad", "return math.sin(true)", err = "bad argument #1 to 'sin' (number expected, got boolean)" },
  { "math.sin.string", "return math.type(math.sin('0')), math.sin('0')", ok = { "string:float", "number:0.0" } },
  { "math.atan.noarg", "return math.atan()", err = "bad argument #1 to 'atan' (number expected, got no value)" },
  { "math.atan.string", "return math.type(math.atan('0')), math.atan('0')", ok = { "string:float", "number:0.0" } },
  { "math.atan.strpair", "return math.type(math.atan('1', '1')), math.atan('1', '1') == math.atan(1, 1)", ok = { "string:float", "boolean:true" } },
  { "math.atan.bad2", "return math.atan(1, true)", err = "bad argument #2 to 'atan' (number expected, got boolean)" },
  { "math.floor.noarg", "return math.floor()", err = "bad argument #1 to 'floor' (number expected, got no value)" },
  { "math.floor.bad", "return math.floor(true)", err = "bad argument #1 to 'floor' (number expected, got boolean)" },
  { "math.floor.string", "return math.type(math.floor('4.5')), math.floor('4.5')", ok = { "string:integer", "number:4" } },
  { "math.ceil.noarg", "return math.ceil()", err = "bad argument #1 to 'ceil' (number expected, got no value)" },
  { "math.ceil.bad", "return math.ceil(true)", err = "bad argument #1 to 'ceil' (number expected, got boolean)" },
  { "math.ceil.string", "return math.type(math.ceil('4.5')), math.ceil('4.5')", ok = { "string:integer", "number:5" } },
  { "math.exp.noarg", "return math.exp()", err = "bad argument #1 to 'exp' (number expected, got no value)" },
  { "math.exp.string", "return math.exp('0')", ok = { "number:1.0" } },
  { "math.cos.bad", "return math.cos(true)", err = "bad argument #1 to 'cos' (number expected, got boolean)" },
  { "math.cos.string", "return math.cos('0')", ok = { "number:1.0" } },
  { "math.tan.noarg", "return math.tan()", err = "bad argument #1 to 'tan' (number expected, got no value)" },
  { "math.tan.string", "return math.tan('0')", ok = { "number:0.0" } },
  { "math.deg.noarg", "return math.deg()", err = "bad argument #1 to 'deg' (number expected, got no value)" },
  { "math.deg.bad", "return math.deg(true)", err = "bad argument #1 to 'deg' (number expected, got boolean)" },
  { "math.deg.string", "return math.deg(tostring(math.pi))", ok = { "number:180.0" } },
  { "math.fmod.noarg", "return math.fmod()", err = "bad argument #2 to 'fmod' (number expected, got no value)" },
  { "math.fmod.nil1", "return math.fmod(nil)", err = "bad argument #2 to 'fmod' (number expected, got no value)" },
  { "math.fmod.nil2", "return math.fmod(nil, 1)", err = "bad argument #1 to 'fmod' (number expected, got nil)" },
  { "math.fmod.zero", "return math.fmod(1, 0)", err = "bad argument #2 to 'fmod' (zero)" },
  { "math.fmod.floatzero", "return math.type(math.fmod(1, 0.0)), math.fmod(1, 0.0)", ok = { "string:float", "number:nan" } },
  { "math.fmod.floatlhszero", "return math.type(math.fmod(1.0, 0)), math.fmod(1.0, 0)", ok = { "string:float", "number:nan" } },
  { "math.fmod.floatarg", "return math.type(math.fmod(5.5, 2)), math.fmod(5.5, 2)", ok = { "string:float", "number:1.5" } },
  { "math.log.noarg", "return math.log()", err = "bad argument #1 to 'log' (number expected, got no value)" },
  { "math.log.badarg", "return math.log(true)", err = "bad argument #1 to 'log' (number expected, got boolean)" },
  { "math.log.badbase", "return math.log(1, true)", err = "bad argument #2 to 'log' (number expected, got boolean)" },
  { "math.log.nilbase", "return math.log(8, nil)", ok = { "number:2.0794415416798" } },
  { "math.log.string", "return math.type(math.log('8')), math.log('8') == math.log(8)", ok = { "string:float", "boolean:true" } },
  { "math.log.strbase", "return math.log(8, '2')", ok = { "number:3.0" } },
  { "math.log.strpair", "return math.type(math.log('8', '2')), math.log('8', '2')", ok = { "string:float", "number:3.0" } },
  { "math.max.string", "return math.max('b', 'a')", ok = { "string:b" } },
  { "math.max.nan", "return math.max(0/0, 1)", ok = { "number:nan" } },
  { "math.max.nansecond", "return math.max(1, 0/0)", ok = { "number:1" } },
  { "math.max.mixed", "return math.max(1, 'a')", err = "attempt to compare number with string" },
  { "math.max.metamethod", "local mt={__lt=function(a,b)return a.v<b.v end}; local a=setmetatable({v=2},mt); local b=setmetatable({v=1},mt); return math.max(a,b).v", ok = { "number:2" } },
  { "math.max.noarg", "return math.max()", err = "bad argument #1 to 'max' (value expected)" },
  { "math.min.string", "return math.min('b', 'a')", ok = { "string:a" } },
  { "math.min.nanfirst", "return math.min(0/0, 1)", ok = { "number:nan" } },
  { "math.min.nansecond", "return math.min(1, 0/0)", ok = { "number:1" } },
  { "math.min.mixed", "return math.min(1, 'a')", err = "attempt to compare string with number" },
  { "math.min.metamethod", "local mt={__lt=function(a,b)return a.v<b.v end}; local a=setmetatable({v=2},mt); local b=setmetatable({v=1},mt); return math.min(a,b).v", ok = { "number:1" } },
  { "math.min.noarg", "return math.min()", err = "bad argument #1 to 'min' (value expected)" },
  { "math.random.frac1", "return math.random(1.2)", err = "bad argument #1 to 'random' (number has no integer representation)" },
  { "math.random.strrange", "return math.type(math.random('1', '1')), math.random('1', '1')", ok = { "string:integer", "number:1" } },
  { "math.random.bad3", "return math.random(1, 2, 3)", err = "wrong number of arguments" },
  { "math.random.zerozero", "return math.random(0, 0)", ok = { "number:0" } },
  { "math.random.empty", "return math.random(10, 5)", err = "bad argument #1 to 'random' (interval is empty)" },
  { "math.random.empty10", "return math.random(1, 0)", err = "bad argument #1 to 'random' (interval is empty)" },
  { "math.random.badarg", "return math.random(true)", err = "bad argument #1 to 'random' (number expected, got boolean)" },
  { "math.randomseed.noarg", "return select('#', math.randomseed())", ok = { "number:2" } },
  { "math.randomseed.bad", "return math.randomseed(true)", err = "bad argument #1 to 'randomseed' (number expected, got boolean)" },
  { "math.randomseed.frac1", "return math.randomseed(1.2)", err = "bad argument #1 to 'randomseed' (number has no integer representation)" },
  { "math.randomseed.frac2", "return math.randomseed(1, 2.2)", err = "bad argument #2 to 'randomseed' (number has no integer representation)" },
  { "math.randomseed.str", "return select('#', math.randomseed('1', '2'))", ok = { "number:2" } },
  { "math.rad.noarg", "return math.rad()", err = "bad argument #1 to 'rad' (number expected, got no value)" },
  { "math.rad.bad", "return math.rad({})", err = "bad argument #1 to 'rad' (number expected, got table)" },
  { "math.rad.string", "return math.rad('180')", ok = { "number:3.1415926535898" } },
  { "math.sqrt.noarg", "return math.sqrt()", err = "bad argument #1 to 'sqrt' (number expected, got no value)" },
  { "math.sqrt.bad", "return math.sqrt(true)", err = "bad argument #1 to 'sqrt' (number expected, got boolean)" },
  { "math.sqrt.string", "return math.sqrt('4')", ok = { "number:2.0" } },
  { "math.modf.noarg", "return math.modf()", err = "bad argument #1 to 'modf' (number expected, got no value)" },
  { "math.modf.bad", "return math.modf(true)", err = "bad argument #1 to 'modf' (number expected, got boolean)" },
  { "math.modf.string", "return math.modf('4.5')", ok = { "number:4", "number:0.5" } },
  { "math.type.noarg", "return math.type()", err = "bad argument #1 to 'type' (value expected)" },
  { "math.type.bool", "return math.type(true)", ok = { "nil:nil" } },
  { "math.type.float", "return math.type(1.0)", ok = { "string:float" } },
  { "math.tointeger.noarg", "return math.tointeger()", err = "bad argument #1 to 'tointeger' (value expected)" },
  { "math.tointeger.string", "return math.tointeger('42')", ok = { "number:42" } },
  { "math.tointeger.strfloat", "return math.tointeger('1.0')", ok = { "number:1" } },
  { "math.tointeger.floatint", "return math.tointeger(42.0)", ok = { "number:42" } },
  { "math.tointeger.maxstr", "return math.type(math.tointeger(tostring(math.maxinteger))), math.tointeger(tostring(math.maxinteger)) == math.maxinteger", ok = { "string:integer", "boolean:true" } },
  { "math.tointeger.frac", "return math.tointeger(1.2)", ok = { "nil:nil" } },
  { "math.tointeger.bad", "return math.tointeger({})", ok = { "nil:nil" } },
  { "math.ult.noarg", "return math.ult()", err = "bad argument #1 to 'ult' (number expected, got no value)" },
  { "math.ult.string", "return math.ult('1', '2')", ok = { "boolean:true" } },
  { "math.ult.floatint", "return math.ult(1.0, 2.0)", ok = { "boolean:true" } },
  { "math.ult.wrap", "return math.ult(-1, 0), math.ult(0, -1)", ok = { "boolean:false", "boolean:true" } },
  { "math.ult.frac1", "return math.ult(1.2, 2)", err = "bad argument #1 to 'ult' (number has no integer representation)" },
  { "math.ult.frac2", "return math.ult(1, 2.2)", err = "bad argument #2 to 'ult' (number has no integer representation)" },
  { "math.fmod.string", "return math.type(math.fmod('5', '2')), math.fmod('5', '2')", ok = { "string:float", "number:1.0" } },

  { "os.clock.extra", "return type(os.clock(true))", ok = { "string:number" } },
  { "os.date.badfmt", "return os.date(true)", err = "bad argument #1 to 'date' (string expected, got boolean)" },
  { "os.date.noarg", "return type(os.date())", ok = { "string:string" } },
  { "os.date.empty", "return os.date('', 0), os.date('!', 0)", ok = { "string:", "string:" } },
  { "os.date.strfmt", "return os.date(1099511627776, 0)", ok = { "string:1099511627776" } },
  { "os.date.nulfmt", "return os.date('\\0\\0', 0) == '\\0\\0', os.date('!\\0\\0', 0) == '\\0\\0'", ok = { "boolean:true", "boolean:true" } },
  { "os.date.strtime", "return os.date('!%Y-%m-%d', '0')", ok = { "string:1970-01-01" } },
  { "os.date.badtimebool", "return os.date('%Y', true)", err = "bad argument #2 to 'date' (number expected, got boolean)" },
  { "os.date.table.utc", "local t = os.date('!*t', 0); return t.year, t.month, t.day, t.hour, t.min, t.sec, t.wday, t.yday, t.isdst", ok = { "number:1970", "number:1", "number:1", "number:0", "number:0", "number:0", "number:5", "number:1", "boolean:false" } },
  { "os.date.table.suffix", "return os.date('*tx', 0)", ok = { "string:*tx" } },
  { "os.date.invalid.Q", "return os.date('%Q', 0)", err = "bad argument #1 to 'date' (invalid conversion specifier '%Q')" },
  { "os.date.win.c", "local win = package.config:sub(1,1) == string.char(92); return (not win) or os.date('%c', 0) == os.date('%x %X', 0), (not win) or os.date('!%c', 0) == os.date('!%x %X', 0)", ok = { "boolean:true", "boolean:true" } },
  { "os.date.win.hash", "local win = package.config:sub(1,1) == string.char(92); return (not win) or os.date('%#c', 0):find('1970', 1, true) ~= nil, (not win) or os.date('%#x', 0):find('1970', 1, true) ~= nil, (not win) or os.date('%#d', 0) == '1'", ok = { "boolean:true", "boolean:true", "boolean:true" } },
  { "os.date.win.invalid.hashX", "local win = package.config:sub(1,1) == string.char(92); local ok, err = pcall(os.date, '%#X', 0); return (not win) or (not ok and err:find(\"invalid conversion specifier '%#X'\", 1, true) ~= nil)", ok = { "boolean:true" } },
  { "os.date.fractime", "return os.date('%Y', 1.5)", err = "bad argument #2 to 'date' (number has no integer representation)" },
  { "os.date.strfractime", "return os.date('%Y', '1.5')", err = "bad argument #2 to 'date' (number has no integer representation)" },
  { "os.date.nulstar", "return os.date('!*t\\0ignored', 0).year", ok = { "number:1970" } },
  { "os.difftime.noarg", "return os.difftime()", err = "bad argument #1 to 'difftime' (number expected, got no value)" },
  { "os.difftime.strint", "return os.difftime('3', '1')", ok = { "number:2.0" } },
  { "os.difftime.bool1", "return os.difftime(true, 1)", err = "bad argument #1 to 'difftime' (number expected, got boolean)" },
  { "os.difftime.bool2", "return os.difftime(1, true)", err = "bad argument #2 to 'difftime' (number expected, got boolean)" },
  { "os.difftime.max", "return os.difftime(math.maxinteger, math.maxinteger - 1)", ok = { "number:1.0" } },
  { "os.difftime.frac1", "return os.difftime(2.5, 1)", err = "bad argument #1 to 'difftime' (number has no integer representation)" },
  { "os.difftime.frac2", "return os.difftime(2, 1.5)", err = "bad argument #2 to 'difftime' (number has no integer representation)" },
  { "os.difftime.strfrac", "return os.difftime('2.5', 1)", err = "bad argument #1 to 'difftime' (number has no integer representation)" },
  { "os.difftime.nil1", "return os.difftime(nil)", err = "bad argument #1 to 'difftime' (number expected, got nil)" },
  { "os.difftime.missing2", "return os.difftime(1)", err = "bad argument #2 to 'difftime' (number expected, got no value)" },
  { "os.execute.noarg", "return os.execute()", ok = { "boolean:true" } },
  { "os.execute.bad", "return os.execute(true)", err = "bad argument #1 to 'execute' (string expected, got boolean)" },
  { "os.exit.bad1", "return os.exit({})", err = "bad argument #1 to 'exit' (number expected, got table)" },
  { "os.exit.badstr", "return os.exit('x')", err = "bad argument #1 to 'exit' (number expected, got string)" },
  { "os.exit.frac", "return os.exit(1.5)", err = "bad argument #1 to 'exit' (number has no integer representation)" },
  { "os.getenv.noarg", "return os.getenv()", err = "bad argument #1 to 'getenv' (string expected, got no value)" },
  { "os.getenv.bad", "return os.getenv(true)", err = "bad argument #1 to 'getenv' (string expected, got boolean)" },
  { "os.getenv.missing", "return os.getenv('LUAJIT_LUA54_STDLIB_EDGES_MISSING_ENV')", ok = { "nil:nil" } },
  { "os.remove.noarg", "return os.remove()", err = "bad argument #1 to 'remove' (string expected, got no value)" },
  { "os.remove.bad", "return os.remove(true)", err = "bad argument #1 to 'remove' (string expected, got boolean)" },
  { "os.remove.missing", "local name='__lua54_edges_remove_missing__'; os.remove(name); local ok,msg,code=os.remove(name); return ok, type(msg), msg:find(name,1,true) ~= nil, type(code), code > 0", ok = { "nil:nil", "string:string", "boolean:true", "string:number", "boolean:true" } },
  { "os.rename.noarg", "return os.rename()", err = "bad argument #1 to 'rename' (string expected, got no value)" },
  { "os.rename.bad2", "return os.rename('x', true)", err = "bad argument #2 to 'rename' (string expected, got boolean)" },
  { "os.rename.missing", "local src='__lua54_edges_rename_missing__'; local dst='__lua54_edges_rename_target__'; os.remove(src); os.remove(dst); local ok,msg,code=os.rename(src,dst); return ok, type(msg), msg:find(src,1,true) == nil, type(code), code > 0", ok = { "nil:nil", "string:string", "boolean:true", "string:number", "boolean:true" } },
  { "os.setlocale.noarg", "return type(os.setlocale())", ok = { "string:string" } },
  { "os.setlocale.nilcat", "return type(os.setlocale(nil, 'time'))", ok = { "string:string" } },
  { "os.setlocale.bad1", "return os.setlocale(true)", err = "bad argument #1 to 'setlocale' (string expected, got boolean)" },
  { "os.setlocale.bad2", "return os.setlocale('', true)", err = "bad argument #2 to 'setlocale' (string expected, got boolean)" },
  { "os.setlocale.badnilcat", "return os.setlocale(nil, 'bad')", err = "bad argument #2 to 'setlocale' (invalid option 'bad')" },
  { "os.setlocale.badcat", "return os.setlocale('', 'bad')", err = "bad argument #2 to 'setlocale' (invalid option 'bad')" },
  { "os.time.bad", "return os.time(true)", err = "bad argument #1 to 'time' (table expected, got boolean)" },
  { "os.time.noargtype", "return math.type(os.time())", ok = { "string:integer" } },
  { "os.time.strymd", "return math.type(os.time{year='2020',month='1',day='1',hour=0,min=0,sec=0})", ok = { "string:integer" } },
  { "os.time.strfield", "return math.type(os.time{year=2020,month=1,day=1,hour='1',min=2,sec=3})", ok = { "string:integer" } },
  { "os.time.monthfrac", "return os.time{year=2020,month=1.5,day=1}", err = "field 'month' is not an integer" },
  { "os.time.daybad", "return os.time{year=2020,month=1,day=true}", err = "field 'day' is not an integer" },
  { "os.time.hourfrac", "return os.time{year=2020,month=1,day=1,hour=1.5}", err = "field 'hour' is not an integer" },
  { "os.time.missyear", "return os.time{hour=12}", err = "field 'year' missing in date table" },
  { "os.time.missmonth", "return os.time{year=2020}", err = "field 'month' missing in date table" },
  { "os.time.missday", "return os.time{year=2020,month=1}", err = "field 'day' missing in date table" },
  { "os.time.minbad", "return os.time{year=2020,month=1,day=1,min=true,sec=true}", err = "field 'min' is not an integer" },
  { "os.time.secbad", "return os.time{year=2020,month=1,day=1,sec=true}", err = "field 'sec' is not an integer" },
  { "os.tmpname.extra", "return type(os.tmpname(true))", ok = { "string:string" } },

  { "package.require.noarg", "return require()", err = "bad argument #1 to 'require' (string expected, got no value)" },
  { "package.require.badbool", "return require(true)", err = "bad argument #1 to 'require' (string expected, got boolean)" },
  { "package.require.loadedtrue", "package.loaded.__probe_true = true; return require('__probe_true')", ok = { "boolean:true" } },
  { "package.require.loadedzero", "package.loaded.__probe_zero = 0; return require('__probe_zero')", ok = { "number:0" } },
  { "package.require.preloadvalue", "local name = '__edge_preload_value'; package.loaded[name] = nil; package.preload[name] = function(modname) return { name = modname }, 'loader-data' end; local mod, data = require(name); local loaded = package.loaded[name]; package.loaded[name] = nil; package.preload[name] = nil; return type(mod), mod.name, data, loaded == mod", ok = { "string:table", "string:__edge_preload_value", "string::preload:", "boolean:true" } },
  { "package.require.searcher.loaderdata", "local name = '__edge_searcher_loaderdata'; local old = package.searchers; local seen_name, seen_data; package.loaded[name] = nil; package.searchers = { function(modname) return function(loader_name, loader_data) seen_name, seen_data = loader_name, loader_data; return { name = loader_name, data = loader_data } end, 'custom-data' end }; local mod, data = require(name); local loaded = package.loaded[name]; package.searchers = old; package.loaded[name] = nil; return type(mod), mod.name, mod.data, data, seen_name, seen_data, loaded == mod", ok = { "string:table", "string:__edge_searcher_loaderdata", "string:custom-data", "string:custom-data", "string:__edge_searcher_loaderdata", "string:custom-data", "boolean:true" } },
  { "package.require.searcher.errorstring", "local old = package.searchers; package.searchers = { function() return 'custom missing' end, function() return nil end }; local ok, err = pcall(require, '__edge_missing_custom__'); package.searchers = old; if ok then error('unexpected success', 0) end; return err", ok = { "string:module '__edge_missing_custom__' not found:\\n\tcustom missing" } },
  { "package.require.searcher.ignoredresult", "local old = package.searchers; package.searchers = { function() return true end, function() return {} end, function() return 'later missing' end }; local ok, err = pcall(require, '__edge_ignored_searcher__'); package.searchers = old; if ok then error('unexpected success', 0) end; return err", ok = { "string:module '__edge_ignored_searcher__' not found:\\n\tlater missing" } },
  { "package.require.preloadnil", "local name = '__edge_preload_nil'; package.loaded[name] = nil; package.preload[name] = function() end; local mod, data = require(name); local again, again_data = require(name); local loaded = package.loaded[name]; package.loaded[name] = nil; package.preload[name] = nil; return mod, data, again, again_data, loaded", ok = { "boolean:true", "string::preload:", "boolean:true", "nil:nil", "boolean:true" } },
  { "package.require.loadedfalse", "local name = '__edge_loaded_false'; local calls = 0; package.loaded[name] = false; package.preload[name] = function() calls = calls + 1; return 'fresh' end; local mod, data = require(name); local loaded = package.loaded[name]; package.loaded[name] = nil; package.preload[name] = nil; return mod, data, loaded, calls", ok = { "string:fresh", "string::preload:", "string:fresh", "number:1" } },
  { "package.require.loadererror", "local name = '__edge_loader_error'; package.loaded[name] = nil; package.preload[name] = function() error('loader boom', 0) end; local ok, err = pcall(require, name); local loaded = package.loaded[name]; package.loaded[name] = nil; package.preload[name] = nil; if ok then error('unexpected success', 0) end; return err, loaded", ok = { "string:loader boom", "nil:nil" } },
  { "package.require.badsearchers", "local old = package.searchers; package.searchers = true; local ok, err = pcall(require, '__probe_missing__'); package.searchers = old; if ok then error('unexpected success', 0) end; error(err, 0)", err = "'package.searchers' must be a table" },
  { "package.loadlib.noarg", "return package.loadlib()", err = "bad argument #1 to 'loadlib' (string expected, got no value)" },
  { "package.loadlib.badfunc", "return package.loadlib('no-such-file', true)", err = "bad argument #2 to 'loadlib' (string expected, got boolean)" },
  { "package.loadlib.badpath", "return package.loadlib(true, 'x')", err = "bad argument #1 to 'loadlib' (string expected, got boolean)" },
  { "package.searchpath.noarg", "return package.searchpath()", err = "bad argument #2 to 'searchpath' (string expected, got no value)" },
  { "package.searchpath.badname", "return package.searchpath(true, '?.lua')", err = "bad argument #1 to 'searchpath' (string expected, got boolean)" },
  { "package.searchpath.badsep", "return package.searchpath('a', '?.lua', true)", err = "bad argument #3 to 'searchpath' (string expected, got boolean)" },
  { "package.searchpath.badrep", "return package.searchpath('a', '?.lua', '.', true)", err = "bad argument #4 to 'searchpath' (string expected, got boolean)" },
  { "package.searchpath.numname", "return package.searchpath(1099511627776, '?.lua')", ok = { "nil:nil", "string:no file '1099511627776.lua'" } },
  { "package.searchpath.numpath", "return package.searchpath('x', 123)", ok = { "nil:nil", "string:no file '123'" } },
  { "package.searchpath.nulname", "return package.searchpath('a\\0b', '?.lua')", ok = { "nil:nil", "string:no file 'a.lua'" } },
  { "package.searchpath.nulpath", "return package.searchpath('a', '?.lua\\0?.txt')", ok = { "nil:nil", "string:no file 'a.lua'" } },
  { "package.searchpath.nilsep", "return package.searchpath('a.b', '?.lua', nil, '/')", ok = { "nil:nil", "string:no file 'a/b.lua'" } },
  { "package.searchpath.dotsep", "return package.searchpath('a.b', '?.lua', '.', '/')", ok = { "nil:nil", "string:no file 'a/b.lua'" } },
  { "package.searchpath.dashsep", "return package.searchpath('a-b', '?.lua', '-', '/')", ok = { "nil:nil", "string:no file 'a/b.lua'" } },
  { "package.searchpath.emptyname", "return package.searchpath('', '?.lua')", ok = { "nil:nil", "string:no file '.lua'" } },
  { "package.searchpath.empty", "return package.searchpath('x', '')", ok = { "nil:nil", "string:no file ''" } },
  { "package.searchpath.multitem", "return package.searchpath('x', '?.lua;?/init.lua')", ok = { "nil:nil", "string:no file 'x.lua'\\n\tno file 'x/init.lua'" } },

  { "string.byte.noarg", "return string.byte()", err = "bad argument #1 to 'byte' (string expected, got no value)" },
  { "string.byte.badidx2", "return string.byte('x', 1, true)", err = "bad argument #3 to 'byte' (number expected, got boolean)" },
  { "string.byte.empty", "return string.byte('')", ok = {} },
  { "string.byte.stridx", "return string.byte('abc', '2', '3')", ok = { "number:98", "number:99" } },
  { "string.byte.fracidx", "return string.byte('abc', 1.2)", err = "bad argument #2 to 'byte' (number has no integer representation)" },
  { "string.byte.rangeempty", "return string.byte('abc', 3, 2)", ok = {} },
  { "string.byte.negidx", "return string.byte('abc', -2, -1)", ok = { "number:98", "number:99" } },
  { "string.byte.zeroidx", "return string.byte('abc', 0, 1)", ok = { "number:97" } },
  { "string.char.noarg", "return string.char()", ok = { "string:" } },
  { "string.char.bounds", "return string.byte(string.char(0, 255), 1, 2)", ok = { "number:0", "number:255" } },
  { "string.char.strcode", "return string.char('65')", ok = { "string:A" } },
  { "string.char.fraccode", "return string.char(65.2)", err = "bad argument #1 to 'char' (number has no integer representation)" },
  { "string.char.bad", "return string.char(0x80000000)", err = "bad argument #1 to 'char' (value out of range)" },
  { "string.dump.noarg", "return string.dump()", err = "bad argument #1 to 'dump' (function expected, got no value)" },
  { "string.dump.strip", "local d1 = string.dump(function(a) return a end, false); local d2 = string.dump(function(a) return a end, true); return type(d1), type(d2), #d2 <= #d1", ok = { "string:string", "string:string", "boolean:true" } },
  { "string.find.noarg", "return string.find()", err = "bad argument #1 to 'find' (string expected, got no value)" },
  { "string.find.capture", "return string.find('abc', '(b)')", ok = { "number:2", "number:2", "string:b" } },
  { "string.find.empty", "return string.find('abc', '')", ok = { "number:1", "number:0" } },
  { "string.find.plain.table", "return string.find('a', 'a', 1, {})", ok = { "number:1", "number:1" } },
  { "string.find.init0", "return string.find('abc', 'a', 0, true)", ok = { "number:1", "number:1" } },
  { "string.find.initstr", "return string.find('abcabc', 'b', '2', true)", ok = { "number:2", "number:2" } },
  { "string.find.initfrac", "return string.find('abc', 'a', 1.2, true)", err = "bad argument #3 to 'find' (number has no integer representation)" },
  { "string.find.initwide", "return string.find('abc', 'a', 1099511627776, true)", ok = { "nil:nil" } },
  { "string.format.noarg", "return string.format()", err = "bad argument #1 to 'format' (string expected, got no value)" },
  { "string.format.missing", "return string.format('%d')", err = "bad argument #2 to 'format' (no value)" },
  { "string.format.badfmt", "return string.format('%999999999999999999999999d', 1)", err = "invalid format (too long)" },
  { "string.format.d.frac", "return string.format('%d', 1.2)", err = "bad argument #2 to 'format' (number has no integer representation)" },
  { "string.format.d.strfrac", "return string.format('%d', '1.2')", err = "bad argument #2 to 'format' (number has no integer representation)" },
  { "string.format.d.floatint", "return string.format('%d', 12.0)", ok = { "string:12" } },
  { "string.format.c.str", "return string.format('%c', '65')", ok = { "string:A" } },
  { "string.format.c.frac", "return string.format('%c', 65.5)", err = "bad argument #2 to 'format' (number has no integer representation)" },
  { "string.format.q.nil", "return string.format('%q', nil)", ok = { "string:nil" } },
  { "string.format.q.true", "return string.format('%q', true)", ok = { "string:true" } },
  { "string.format.q.false", "return string.format('%q', false)", ok = { "string:false" } },
  { "string.format.q.nan", "return string.format('%q', 0/0)", ok = { "string:(0/0)" } },
  { "string.format.q.inf", "return string.format('%q', math.huge)", ok = { "string:1e9999" } },
  { "string.format.q.integer", "return string.format('%q', 42)", ok = { "string:42" } },
  { "string.format.q.float", "return string.format('%q', 1.5)", ok = { "string:0x1.8p+0" } },
  { "string.format.q.negzero", "return string.format('%q', -0.0)", ok = { "string:-0x0p+0" } },
  { "string.format.q.neginf", "return string.format('%q', -math.huge)", ok = { "string:-1e9999" } },
  { "string.format.q.mininteger", "return string.format('%q', math.mininteger)", ok = { "string:0x8000000000000000" } },
  { "string.format.q.strnul", "return string.format('%q', 'a' .. string.char(0) .. 'b')", ok = { "string:\"a\\0b\"" } },
  { "string.format.q.strctldigit", "return string.format('%q', 'a' .. string.char(1) .. '2')", ok = { "string:\"a\\0012\"" } },
  { "string.format.q.strquote", "return string.format('%q', 'a\"b')", ok = { "string:\"a\\\"b\"" } },
  { "string.format.q.strbackslash", "return string.format('%q', 'a\\\\b')", ok = { "string:\"a\\\\b\"" } },
  { "string.format.q.strnewline", "return string.format('%q', 'a\\nb')", ok = { "string:\"a\\\\nb\"" } },
  { "string.format.q.table", "return string.format('%q', {})", err = "bad argument #2 to 'format' (value has no literal form)" },
  { "string.format.invalid.I", "return string.format('%I', 1)", err = "invalid conversion '%I' to 'format'" },
  { "string.format.invalid.pspec", "return string.format('%3.1p', {})", err = "invalid conversion specification: '%3.1p'" },
  { "string.format.mod.a", "return string.format('%#a', 1.5)", err = "modifiers for format '%a'/'%A' not implemented" },
  { "string.format.percent", "return string.format('%%')", ok = { "string:%" } },
  { "string.format.s.number", "return string.format('%s', 12.0)", ok = { "string:12.0" } },
  { "string.format.s.boolnil", "return string.format('%s:%s', true, nil)", ok = { "string:true:nil" } },
  { "string.format.s.nulwidth", "return string.format('%10s', '\\0')", err = "bad argument #2 to 'format' (string contains zeros)" },
  { "string.gmatch.noarg", "return string.gmatch()", err = "bad argument #1 to 'gmatch' (string expected, got no value)" },
  { "string.gmatch.capture", "local it = string.gmatch('ab cd', '(%a)(%a)'); local a, b = it(); local c, d = it(); return a, b, c, d", ok = { "string:a", "string:b", "string:c", "string:d" } },
  { "string.gmatch.empty", "local it = string.gmatch('ab', ''); return it(), it(), it()", ok = { "string:", "string:", "string:" } },
  { "string.gmatch.init", "local it = string.gmatch('abc', '.', 2); return it(), it()", ok = { "string:b", "string:c" } },
  { "string.gmatch.initstr", "local it = string.gmatch('abcabc', 'b.', '2'); return it(), it()", ok = { "string:bc", "string:bc" } },
  { "string.gmatch.initfrac", "return string.gmatch('abc', '.', 1.2)", err = "bad argument #3 to 'gmatch' (number has no integer representation)" },
  { "string.gmatch.badinit", "return string.gmatch('abc', '.', true)", err = "bad argument #3 to 'gmatch' (number expected, got boolean)" },
  { "string.gsub.norepl", "return string.gsub('a', 'a')", err = "bad argument #3 to 'gsub' (string/function/table expected, got no value)" },
  { "string.gsub.nilrepl", "return string.gsub('alo', '.', nil)", err = "bad argument #3 to 'gsub' (string/function/table expected, got nil)" },
  { "string.gsub.boolrepl", "return string.gsub('alo', '.', true)", err = "bad argument #3 to 'gsub' (string/function/table expected, got boolean)" },
  { "string.gsub.numrepl", "return string.gsub('a', 'a', 1)", ok = { "string:1", "number:1" } },
  { "string.gsub.tablemissing", "return string.gsub('ab', '.', {a='x'})", ok = { "string:xb", "number:2" } },
  { "string.gsub.tablefalse", "return string.gsub('ab', '.', {a=false,b='y'})", ok = { "string:ay", "number:2" } },
  { "string.gsub.tablezero", "return string.gsub('ab', '.', { a = 0, b = 'x' })", ok = { "string:0x", "number:2" } },
  { "string.gsub.funfalse", "return string.gsub('ab', '.', function(c) if c == 'a' then return false else return 'y' end end)", ok = { "string:ay", "number:2" } },
  { "string.gsub.funnil", "return string.gsub('ab', '.', function(c) if c == 'a' then return nil else return 'y' end end)", ok = { "string:ay", "number:2" } },
  { "string.gsub.badcap.repl", "return string.gsub('alo', '.', '%2')", err = "invalid capture index %2" },
  { "string.gsub.badcap.pattern0", "return string.gsub('alo', '(%0)', 'a')", err = "invalid capture index %0" },
  { "string.gsub.badcap.pattern1", "return string.gsub('alo', '(%1)', 'a')", err = "invalid capture index %1" },
  { "string.gsub.badpct.x", "return string.gsub('alo', '.', '%x')", err = "invalid use of '%' in replacement string" },
  { "string.gsub.badpct.end", "return string.gsub('alo', '.', '%')", err = "invalid use of '%' in replacement string" },
  { "string.gsub.empty", "return string.gsub('a b cd', ' *', '-')", ok = { "string:-a-b-c-d-", "number:5" } },
  { "string.gsub.limit0", "return string.gsub('aaa', 'a', 'x', 0)", ok = { "string:aaa", "number:0" } },
  { "string.gsub.limitstr", "return string.gsub('aaa', 'a', 'x', '2')", ok = { "string:xxa", "number:2" } },
  { "string.gsub.limitneg", "return string.gsub('aaa', 'a', 'x', -1)", ok = { "string:aaa", "number:0" } },
  { "string.gsub.limitstrneg", "return string.gsub('aaa', 'a', 'x', '-1')", ok = { "string:aaa", "number:0" } },
  { "string.gsub.limitwide", "return string.gsub('aaa', 'a', 'x', 1099511627776)", ok = { "string:xxx", "number:3" } },
  { "string.gsub.limitfrac", "return string.gsub('aaa', 'a', 'x', 1.2)", err = "bad argument #4 to 'gsub' (number has no integer representation)" },
  { "string.len.noarg", "return string.len()", err = "bad argument #1 to 'len' (string expected, got no value)" },
  { "string.len.number", "return string.len(12345)", ok = { "number:5" } },
  { "string.lower.noarg", "return string.lower()", err = "bad argument #1 to 'lower' (string expected, got no value)" },
  { "string.lower.number", "return string.lower(12345)", ok = { "string:12345" } },
  { "string.find.bmiss", "return string.find('a', '%b')", err = "malformed pattern (missing arguments to '%b')" },
  { "string.find.bmissing2", "return string.find('a', '%ba')", err = "malformed pattern (missing arguments to '%b')" },
  { "string.match.noarg", "return string.match()", err = "bad argument #1 to 'match' (string expected, got no value)" },
  { "string.match.capture", "return string.match('abc', 'a(.)c')", ok = { "string:b" } },
  { "string.match.initneg", "return string.match('abc', 'b', -2)", ok = { "string:b" } },
  { "string.match.init0", "return string.match('abc', 'a', 0)", ok = { "string:a" } },
  { "string.match.initstr", "return string.match('abcabc', 'b.', '2')", ok = { "string:bc" } },
  { "string.match.initfrac", "return string.match('abc', 'a', 1.2)", err = "bad argument #3 to 'match' (number has no integer representation)" },
  { "string.pack.noarg", "return string.pack()", err = "bad argument #1 to 'pack' (string expected, got no value)" },
  { "string.pack.badfmt", "return string.pack('z')", err = "bad argument #2 to 'pack' (string expected, got nil)" },
  { "string.pack.missing", "return string.pack('i')", err = "bad argument #2 to 'pack' (number expected, got nil)" },
  { "string.pack.strint", "local s = string.pack('b', '65'); return string.unpack('b', s)", ok = { "number:65", "number:2" } },
  { "string.pack.fracint", "return string.pack('b', 1.2)", err = "bad argument #2 to 'pack' (number has no integer representation)" },
  { "string.pack.Xspace", "return string.pack('X i', 1)", err = "bad argument #1 to 'pack' (invalid next option for option 'X')" },
  { "string.packsize.badfmt", "return string.packsize('z')", err = "bad argument #1 to 'packsize' (variable-length format)" },
  { "string.packsize.cnosize", "return string.packsize('c')", err = "missing size for format option 'c'" },
  { "string.packsize.align0", "return string.packsize('!0')", err = "integral size (0) out of limits [1,16]" },
  { "string.packsize.align17", "return string.packsize('!17')", err = "integral size (17) out of limits [1,16]" },
  { "string.rep.noarg", "return string.rep()", err = "bad argument #1 to 'rep' (string expected, got no value)" },
  { "string.rep.sep", "return string.rep('a', 3, ',')", ok = { "string:a,a,a" } },
  { "string.rep.strcount", "return string.rep('a', '3')", ok = { "string:aaa" } },
  { "string.rep.fraccount", "return string.rep('a', 1.2)", err = "bad argument #2 to 'rep' (number has no integer representation)" },
  { "string.rep.zero", "return string.rep('a', 0, ',')", ok = { "string:" } },
  { "string.rep.neg", "return string.rep('a', -1)", ok = { "string:" } },
  { "string.rep.badsep", "return string.rep('a', 2, true)", err = "bad argument #3 to 'rep' (string expected, got boolean)" },
  { "string.reverse.noarg", "return string.reverse()", err = "bad argument #1 to 'reverse' (string expected, got no value)" },
  { "string.reverse.nul", "return string.reverse('a\\0b')", ok = { "string:b\0a" } },
  { "string.sub.noarg", "return string.sub()", err = "bad argument #1 to 'sub' (string expected, got no value)" },
  { "string.sub.negidx", "return string.sub('abc', -2, -1)", ok = { "string:bc" } },
  { "string.sub.stridx", "return string.sub('abc', '2', '3')", ok = { "string:bc" } },
  { "string.sub.fracidx", "return string.sub('abc', 1.2)", err = "bad argument #2 to 'sub' (number has no integer representation)" },
  { "string.upper.noarg", "return string.upper()", err = "bad argument #1 to 'upper' (string expected, got no value)" },
  { "string.upper.number", "return string.upper(12345)", ok = { "string:12345" } },
  { "string.unpack.noarg", "return string.unpack()", err = "bad argument #1 to 'unpack' (string expected, got no value)" },
  { "string.unpack.short", "return string.unpack('i4', '')", err = "bad argument #2 to 'unpack' (data string too short)" },
  { "string.unpack.pos0", "return string.unpack('b', 'abc', 0)", ok = { "number:97", "number:2" } },
  { "string.unpack.negzero", "return string.unpack('b', 'abc', -0)", ok = { "number:97", "number:2" } },
  { "string.unpack.strpos", "return string.unpack('b', 'abc', '2')", ok = { "number:98", "number:3" } },
  { "string.unpack.fracpos", "return string.unpack('b', 'abc', 1.2)", err = "bad argument #3 to 'unpack' (number has no integer representation)" },
  { "string.unpack.pos5", "return string.unpack('b', 'abc', 5)", err = "bad argument #3 to 'unpack' (initial position out of string)" },
  { "string.unpack.negtail", "return string.unpack('b', 'abc', -1)", ok = { "number:99", "number:4" } },
  { "string.unpack.wideneg", "return string.unpack('b', 'abc', -1099511627776)", ok = { "number:97", "number:2" } },

  { "table.concat.noarg", "return table.concat()", err = "bad argument #1 to 'concat' (table expected, got no value)" },
  { "table.concat.badsep", "return table.concat({}, true)", err = "bad argument #2 to 'concat' (string expected, got boolean)" },
  { "table.concat.emptyrange", "return table.concat({'a'}, ',', 2, 1)", ok = { "string:" } },
  { "table.concat.stridx", "return table.concat({'a','b','c'}, ',', '2', '3')", ok = { "string:b,c" } },
  { "table.concat.fracidx", "return table.concat({'a'}, ',', 1.2)", err = "bad argument #3 to 'concat' (number has no integer representation)" },
  { "table.concat.fracfinal", "return table.concat({'a'}, ',', 1, 1.2)", err = "bad argument #4 to 'concat' (number has no integer representation)" },
  { "table.concat.one", "return table.concat({'a'}, ',')", ok = { "string:a" } },
  { "table.concat.empty", "return table.concat({}, ',')", ok = { "string:" } },
  { "table.concat.numsep", "return table.concat({'a','b'}, 1)", ok = { "string:a1b" } },
  { "table.concat.numbers", "return table.concat({1, 2.0}, ',')", ok = { "string:1,2.0" } },
  { "table.concat.nilhole", "return table.concat({1,nil,3}, ',')", err = "invalid value (nil) at index 2 in table for 'concat'" },
  { "table.concat.floatint", "return table.concat({1.0,2}, ',')", ok = { "string:1.0,2" } },
  { "table.concat.boolitem", "return table.concat({true})", err = "invalid value (boolean) at index 1 in table for 'concat'" },
  { "table.proxy.helpers", "local old = debug.getmetatable(0); local slots = {}; debug.setmetatable(0, { __len = function(self) return #slots[self] end, __index = function(self, k) return slots[self][k] end, __newindex = function(self, k, v) slots[self][k] = v end }); local ok, joined, inserted, removed, shifted, sorted, u, v, x, y, z = pcall(function() slots[0] = { 'a', 'b' }; local joined = table.concat(0, ','); slots[0] = { 'b', 'c' }; table.insert(0, 1, 'a'); local inserted = slots[0][1] .. slots[0][2] .. slots[0][3]; local removed = table.remove(0, 2); local shifted = slots[0][2]; slots[0] = { 3, 1, 2 }; table.sort(0); local sorted = slots[0][1] .. slots[0][2] .. slots[0][3]; slots[0] = { 'u', 'v' }; local u, v = table.unpack(0); slots[0] = { 'x', nil, 'z' }; local x, y, z = table.unpack(0, 1, 3); return joined, inserted, removed, shifted, sorted, u, v, x, y, z end); debug.setmetatable(0, old); if not ok then error(joined, 0) end; return joined, inserted, removed, shifted, sorted, u, v, x, y, z", ok = { "string:a,b", "string:abc", "string:b", "string:c", "string:123", "string:u", "string:v", "string:x", "nil:nil", "string:z" } },
  { "table.insert.noarg", "return table.insert()", err = "bad argument #1 to 'insert' (table expected, got no value)" },
  { "table.insert.append", "local t = { 1 }; return table.insert(t, 'x'), t[1], t[2], #t", ok = { "nil:nil", "number:1", "string:x", "number:2" } },
  { "table.insert.nilvalue", "local t = { 1 }; return table.insert(t, nil), t[1], t[2], #t", ok = { "nil:nil", "number:1", "nil:nil", "number:1" } },
  { "table.insert.badpos", "return table.insert({1,2}, 1.2, 'x')", err = "bad argument #2 to 'insert' (number has no integer representation)" },
  { "table.insert.toomany", "return table.insert({}, 1, 2, 3)", err = "wrong number of arguments to 'insert'" },
  { "table.insert.nontable", "return table.insert(1, 2)", err = "bad argument #1 to 'insert' (table expected, got number)" },
  { "table.insert.pos0", "return table.insert({1}, 0, 'x')", err = "bad argument #2 to 'insert' (position out of bounds)" },
  { "table.insert.pos2", "local t = {1}; table.insert(t, 2, 'x'); return table.concat(t, ',')", ok = { "string:1,x" } },
  { "table.insert.strpos", "local t = {1}; table.insert(t, '2', 'x'); return table.concat(t, ',')", ok = { "string:1,x" } },
  { "table.insert.pos3", "return table.insert({1}, 3, 'x')", err = "bad argument #2 to 'insert' (position out of bounds)" },
  { "table.move.noarg", "return table.move()", err = "bad argument #2 to 'move' (number expected, got no value)" },
  { "table.move.badfrom", "return table.move({}, 1.2, 2, 1)", err = "bad argument #2 to 'move' (number has no integer representation)" },
  { "table.move.badto", "return table.move({}, 1, 2.2, 1)", err = "bad argument #3 to 'move' (number has no integer representation)" },
  { "table.move.baddest", "return table.move({}, 1, 2, 1.2)", err = "bad argument #4 to 'move' (number has no integer representation)" },
  { "table.move.stridx", "return table.move({}, '1', '2', '3')", ok = { "table" } },
  { "table.move.stridx.copy", "local t = {1,2,3}; return table.move(t, '1', '2', '2') == t, table.concat(t, ',')", ok = { "boolean:true", "string:1,1,2" } },
  { "table.move.wrap", "return table.move({}, 1, math.maxinteger, 2)", err = "bad argument #4 to 'move' (destination wrap around)" },
  { "table.move.target", "local a = { 1, 2 }; local b = {}; return table.move(a, 1, 2, 3, b) == b, b[3], b[4], a[1]", ok = { "boolean:true", "number:1", "number:2", "number:1" } },
  { "table.move.empty", "local t = { 1 }; return table.move(t, 2, 1, 100) == t, t[100]", ok = { "boolean:true", "nil:nil" } },
  { "table.move.emptytarget", "local t = { 1 }; local b = {}; return table.move(t, 2, 1, 100, b) == b, next(b)", ok = { "boolean:true", "nil:nil" } },
  { "table.move.same", "local t = {1,2,3}; return table.move(t, 1, 3, 1) == t, table.concat(t, ',')", ok = { "boolean:true", "string:1,2,3" } },
  { "table.move.overlap.right", "local t = {1,2,3,4}; return table.move(t, 1, 3, 2) == t, table.concat(t, ',')", ok = { "boolean:true", "string:1,1,2,3" } },
  { "table.move.overlap.left", "local t = {1,2,3,4}; return table.move(t, 2, 4, 1) == t, table.concat(t, ',')", ok = { "boolean:true", "string:2,3,4,4" } },
  { "table.move.proxy", "local old = debug.getmetatable(0); local slots = {}; local reads, writes = 0, 0; debug.setmetatable(0, { __index = function(self, k) reads = reads + 1; return slots[self][k] end, __newindex = function(self, k, v) writes = writes + 1; slots[self][k] = v end }); local ok, target, a, b = pcall(function() slots[0] = { 'x', 'y' }; slots[1] = {}; local target = table.move(0, 1, 2, 3, 1); return target, slots[1][3], slots[1][4] end); debug.setmetatable(0, old); if not ok then error(target, 0) end; return target == 1, a, b, reads, writes", ok = { "boolean:true", "string:x", "string:y", "number:2", "number:2" } },
  { "table.move.badtarget", "return table.move({}, 1, 2, 1, true)", err = "bad argument #5 to 'move' (table expected, got boolean)" },
  { "table.move.emptybadtarget", "return table.move({}, 2, 1, 1, true)", err = "bad argument #5 to 'move' (table expected, got boolean)" },
  { "table.pack.empty", "local t = table.pack(); return t.n, next(t)", ok = { "number:0", "string:n", "number:0" } },
  { "table.pack.nilhole", "local t = table.pack(nil, 'x'); return t.n, t[1], t[2]", ok = { "number:2", "nil:nil", "string:x" } },
  { "table.pack.extra", "return table.pack(1, nil, 3).n", ok = { "number:3" } },
  { "table.pack.values", "local t = table.pack(1, nil, 3); return t.n, t[1], t[2], t[3]", ok = { "number:3", "number:1", "nil:nil", "number:3" } },
  { "table.remove.noarg", "return table.remove()", err = "bad argument #1 to 'remove' (table expected, got no value)" },
  { "table.remove.pos0", "return table.remove({1}, 0)", err = "bad argument #2 to 'remove' (position out of bounds)" },
  { "table.remove.strpos", "local t = {1}; return table.remove(t, '1'), #t", ok = { "number:1", "number:0" } },
  { "table.remove.strpos2", "local t = {1,2,3}; return table.remove(t, '2'), table.concat(t, ',')", ok = { "number:2", "string:1,3" } },
  { "table.remove.fracpos", "return table.remove({1}, 1.2)", err = "bad argument #2 to 'remove' (number has no integer representation)" },
  { "table.remove.empty", "local t = {}; return table.remove(t)", ok = { "nil:nil" } },
  { "table.remove.zerokey", "local t = {[0] = 'ban'}; local v = table.remove(t); return v, t[0]", ok = { "string:ban", "nil:nil" } },
  { "table.remove.pos2", "return table.remove({1}, 2)", ok = { "nil:nil" } },
  { "table.sort.noarg", "return table.sort()", err = "bad argument #1 to 'sort' (table expected, got no value)" },
  { "table.sort.badcomp", "return table.sort({}, true)", ok = {} },
  { "table.sort.badcomp.one", "local t = {1}; return table.sort(t, true), t[1]", ok = { "nil:nil", "number:1" } },
  { "table.sort.badcomp2", "return table.sort({2,1}, true)", err = "bad argument #2 to 'sort' (function expected, got boolean)" },
  { "table.sort.normal", "local t = {3,1,2}; return table.sort(t), table.concat(t, ',')", ok = { "nil:nil", "string:1,2,3" } },
  { "table.sort.desc", "local t = {1,3,2}; return table.sort(t, function(a,b) return a > b end), table.concat(t, ',')", ok = { "nil:nil", "string:3,2,1" } },
  { "table.sort.compeq", "local t = { 1, 1 }; return table.sort(t, function(a, b) return a <= b end)", ok = {} },
  { "table.sort.cmperror", "return table.sort({2,1}, function() error('cmp boom', 0) end)", err = "cmp boom" },
  { "table.sort.baditems", "return table.sort({ {}, {} })", err = "attempt to compare two table values" },
  { "table.unpack.noarg", "return table.unpack()", err = "attempt to get length of a nil value" },
  { "table.unpack.default", "return table.unpack({ 1, nil, 3 })", ok = { "number:1", "nil:nil", "number:3" } },
  { "table.unpack.nilhole", "return table.unpack({nil,2}, 1, 2)", ok = { "nil:nil", "number:2" } },
  { "table.unpack.stridx", "return table.unpack({1,2,3}, '2', '3')", ok = { "number:2", "number:3" } },
  { "table.unpack.fracidx", "return table.unpack({1,2,3}, 1.2, 3)", err = "bad argument #2 to 'unpack' (number has no integer representation)" },
  { "table.unpack.emptyrange", "return table.unpack({}, 2, 1)", ok = {} },
  { "table.unpack.limit0", "return select('#', table.unpack({ 1 }, 1, 0))", ok = { "number:0" } },
  { "table.unpack.nontable.emptyrange", "return select('#', table.unpack(1, 2, 1))", ok = { "number:0" } },
  { "table.unpack.nontable.read", "return table.unpack(1, 1, 1)", err = "attempt to index a number value" },

  { "utf8.char.noarg", "return utf8.char()", ok = { "string:" } },
  { "utf8.char.ascii", "return utf8.char(65)", ok = { "string:A" } },
  { "utf8.char.multi", "return utf8.codepoint(utf8.char(65, 0x20ac), 1, -1)", ok = { "number:65", "number:8364" } },
  { "utf8.char.str", "return utf8.char('65')", ok = { "string:A" } },
  { "utf8.char.frac", "return utf8.char(65.5)", err = "bad argument #1 to 'char' (number has no integer representation)" },
  { "utf8.char.bad", "return utf8.char(0x80000000)", err = "bad argument #1 to 'char' (value out of range)" },
  { "utf8.codes.noarg", "return utf8.codes()", err = "bad argument #1 to 'codes' (string expected, got no value)" },
  { "utf8.codes.valid", "local iter, s, n = utf8.codes('A\\194\\162'); local p1, c1 = iter(s, n); local p2, c2 = iter(s, p1); return p1, c1, p2, c2", ok = { "number:1", "number:65", "number:2", "number:162" } },
  { "utf8.codes.invalid", "for _ in utf8.codes('\\128') do end; return true", err = "bad argument #1 to 'codes' (invalid UTF-8 code)" },
  { "utf8.codes.laxinvalid", "local iter, s, n = utf8.codes('\\255', true); return iter(s, n)", err = "invalid UTF-8 code" },
  { "utf8.codes.laxarg", "return utf8.codes('a', {})", ok = { "function", "string:a", "number:0" } },
  { "utf8.codepoint.noarg", "return utf8.codepoint()", err = "bad argument #1 to 'codepoint' (string expected, got no value)" },
  { "utf8.codepoint.default", "return utf8.codepoint('A\\194\\162')", ok = { "number:65" } },
  { "utf8.codepoint.multi", "return utf8.codepoint('A\\194\\162', 1, 2)", ok = { "number:65", "number:162" } },
  { "utf8.codepoint.neg", "return utf8.codepoint('abc', -2, -1)", ok = { "number:98", "number:99" } },
  { "utf8.codepoint.badidx", "return utf8.codepoint('abc', 0, 1)", err = "bad argument #2 to 'codepoint' (out of bounds)" },
  { "utf8.codepoint.badfinal", "return utf8.codepoint('abc', 1, 4)", err = "bad argument #3 to 'codepoint' (out of bounds)" },
  { "utf8.codepoint.stridx", "return utf8.codepoint('abc', '2', '3')", ok = { "number:98", "number:99" } },
  { "utf8.codepoint.fracidx", "return utf8.codepoint('abc', 1.2)", err = "bad argument #2 to 'codepoint' (number has no integer representation)" },
  { "utf8.codepoint.emptyrange", "return utf8.codepoint('abc', 3, 2)", ok = {} },
  { "utf8.len.noarg", "return utf8.len()", err = "bad argument #1 to 'len' (string expected, got no value)" },
  { "utf8.len.badidx", "return utf8.len('abc', 0, 2)", err = "bad argument #2 to 'len' (initial position out of bounds)" },
  { "utf8.len.badfinal", "return utf8.len('abc', 1, 4)", err = "bad argument #3 to 'len' (final position out of bounds)" },
  { "utf8.len.stridx", "return utf8.len('abc', '2', '3')", ok = { "number:2" } },
  { "utf8.len.fracidx", "return utf8.len('abc', 1.2)", err = "bad argument #2 to 'len' (number has no integer representation)" },
  { "utf8.len.emptyrange", "return utf8.len('abc', 3, 2)", ok = { "number:0" } },
  { "utf8.len.invalid", "return utf8.len('a\\255b')", ok = { "nil:nil", "number:2" } },
  { "utf8.len.laxinvalid", "return utf8.len('a\\255b', 1, -1, true)", ok = { "nil:nil", "number:2" } },
  { "utf8.len.laxarg", "return utf8.len('a', 1, -1, {})", ok = { "number:1" } },
  { "utf8.offset.noarg", "return utf8.offset()", err = "bad argument #1 to 'offset' (string expected, got no value)" },
  { "utf8.offset.badn", "return utf8.offset('abc', 1.2)", err = "bad argument #2 to 'offset' (number has no integer representation)" },
  { "utf8.offset.badn.bool", "return utf8.offset('a', true)", err = "bad argument #2 to 'offset' (number expected, got boolean)" },
  { "utf8.offset.strargs", "return utf8.offset('abc', '2', '1')", ok = { "number:2" } },
  { "utf8.offset.neg", "return utf8.offset('abc', -1)", ok = { "number:3" } },
  { "utf8.offset.second", "return utf8.offset('A\\194\\162', 2)", ok = { "number:2" } },
  { "utf8.offset.frompos", "return utf8.offset('abc', 2, 2)", ok = { "number:3" } },
  { "utf8.offset.afterend", "return utf8.offset('abc', 1, 4)", ok = { "number:4" } },
  { "utf8.offset.zero.cont", "return utf8.offset('\194\128', 0, 2)", ok = { "number:1" } },
  { "utf8.offset.contpos", "return utf8.offset('\\194\\162', 1, 2)", err = "initial position is a continuation byte" },
  { "utf8.offset.pos0", "return utf8.offset('abc', 1, 0)", err = "bad argument #3 to 'offset' (position out of bounds)" },
}

local function normerr(e)
  e = tostring(e)
  e = e:gsub('^%[string "[^"]*"%]:%d+: ', '')
  e = e:gsub('^[^:]+:%d+: ', '')
  return e
end

local function val(v)
  local tv = type(v)
  if tv == "string" then return "string:" .. v:gsub("\n", "\\n") end
  if tv == "number" or tv == "boolean" or tv == "nil" then
    return tv .. ":" .. tostring(v)
  end
  return tv
end

for _, c in ipairs(cases) do
  local name, code = c[1], c[2]
  local f, err = load(code, "=" .. name)
  assert(f, name .. " load failed: " .. tostring(err))
  local r = table.pack(pcall(f))
  if c.err then
    assert(not r[1], name .. " unexpectedly succeeded")
    local got = normerr(r[2])
    assert(got == c.err, name .. " error mismatch\nwant: " .. c.err .. "\n got: " .. got)
  else
    assert(r[1], name .. " unexpectedly failed: " .. normerr(r[2]))
    assert(r.n - 1 == #c.ok,
      name .. " result count mismatch: want " .. #c.ok .. ", got " .. (r.n - 1))
    for i = 1, #c.ok do
      local got = val(r[i + 1])
      assert(got == c.ok[i],
        name .. " result #" .. i .. " mismatch: want " .. c.ok[i] .. ", got " .. got)
    end
  end
end

print("lua54_stdlib_edges.lua OK")
